
version: "3.7"

services:
  proxy:
    container_name: mynginx
    depends_on:
      - wp
      - db
    build: requirements/nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    networks:
      - frontend
    volumes:
      - wp_data:/www
  
  wp:
    container_name: mywp
    depends_on:
      - db
    build: requirements/wordpress
    restart: always
    networks:
      - frontend
      - backend
    volumes:
      - wp_data:/www
    env_file:
      - .env

  db:
    container_name: mydb
    build: requirements/mariadb
    restart: always
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db_data:
  wp_data:

#default volumes path: /var/lib/docker/volumes/
    
# env_file:
#   - path: ./srcs/.env