
version: "3.7"

services:
  nginx:
    container_name: proxy_server
    depends_on:
      - wordpress
      - db
    build: ./srcs/requirements/nginx/Dockerfile
    restart: always
    ports:
      - "443:443"
      - "80:80" #TODO
    networks:
      - frontend
    volumes:
      - wp_data:/var/www/html
  
  wordpress:
    container_name: wp
    depends_on:
      - db
    build: ./srcs/requirements/wordpress/Dockerfile
    restart: always
    networks:
      - frontend
      - backend
    volumes:
      -wp_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST: $(WORDPRESS_DB_HOST)
      - WORDPRESS_DB_USER: $(WORDPRESS_DB_USER)
      - WORDPRESS_DB_PASSWORD: $(WORDPRESS_DB_PASSWORD)
      - WORDPRESS_DB_NAME: $(WORDPRESS_DB_NAME)

  db:
    container_name: mydb
    build: ./srcs/requirements/mariadb/Dockerfile
    restart: always
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
      - MYSQL_USER: $(MYSQL_USER)
      - MYSQL_DATABASE: $(MYSQL_DATABASE)
      - MYSQL_PASSWORD: $(MYSQL_PASSWORD)

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db_data:
  wp_data:

#default volumes path: /var/lib/docker/volumes/
    
# env_file:
#   - path: ./srcs/.env