
version: "3.7"

services:
  nginx:
    container_name: proxy_server
    depends_on:
      - wordpress
      - db
    build: ./requirements/nginx/Dockerfile
    restart: always
    ports:
      - "443:443"
      - "80:80" #TODO
    networks:
      - frontend
    volumes:
      - wp_data:/www/html
  
  wordpress:
    container_name: wp
    depends_on:
      - db
    build: ./requirements/wordpress/Dockerfile
    restart: always
    networks:
      - frontend
      - backend
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env

  db:
    container_name: mydb
    build: ./requirements/mariadb/Dockerfile
    restart: always
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db_data:
  wp_data:

#default volumes path: /var/lib/docker/volumes/
    
# env_file:
#   - path: ./srcs/.env