
version: "3.7"

services:
  proxy:
    depends_on:
      - wp
      - db
    build: requirements/nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - my_net 
    volumes:
      - wp_data:/www/wordpress
  
  wp:
    depends_on:
      - db
    build: requirements/wordpress
    restart: always
    networks:
      - my_net 
    volumes:
      - wp_data:/www/wordpress
    env_file:
      - .env

  db:
    build: requirements/mariadb
    restart: always
    networks:
      - my_net
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

networks:
  my_net:
    driver: bridge

volumes:
  db_data:
  wp_data:

#default volumes path: /var/lib/docker/volumes/
    
# env_file:
#   - path: ./srcs/.env